name: CI

on:
  push:
    branches: [develop, main]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - run: dotnet restore WorkoutTracker.slnx
      - run: dotnet build WorkoutTracker.slnx --no-restore --configuration Release
      - run: dotnet test WorkoutTracker.slnx --no-build --configuration Release
